name: Sync data

on:
  workflow_call:

jobs:
  sync-data:
    name: Sync data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download data
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd Data
          gh run download -n data || echo '{}' > data.json
      - name: Update data
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd Data
          npm ci
          npx tsx sync
      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: Data/data.json
          retention-days: 5
          compression-level: 9
